"""File upload/serve use cases (file-uploads spec).

Images (uploaded by users or generated by the agent) are stored in blob storage
under a per-workspace key and served back to workspace members. Uploads are
size-capped and validated by magic bytes — the declared content type is not
trusted — and only raster images are accepted, so an SVG/script payload cannot be
stored and later served with an image content type.
"""

from __future__ import annotations

from dataclasses import dataclass

from cyberarche.application.authz import AccessControl
from cyberarche.application.kernel import CallerContext
from cyberarche.application.ports.storage import Blob, BlobStoragePort
from cyberarche.application.ports.telemetry import IdPort
from cyberarche.domain.errors import ValidationFailed
from cyberarche.domain.ids import WorkspaceId
from cyberarche.domain.memberships import Role

MAX_IMAGE_BYTES = 10 * 1024 * 1024  # 10 MB


@dataclass(frozen=True, slots=True)
class UploadedFile:
    id: str
    url: str
    content_type: str


def _sniff_image_type(content: bytes) -> str | None:
    """Return a supported image MIME by inspecting magic bytes, or None."""
    if content.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if content.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if content.startswith(b"GIF87a") or content.startswith(b"GIF89a"):
        return "image/gif"
    if len(content) >= 12 and content[0:4] == b"RIFF" and content[8:12] == b"WEBP":
        return "image/webp"
    return None


def _file_key(workspace_id: WorkspaceId, file_id: str) -> str:
    return f"files/{workspace_id}/{file_id}"


class FileUseCases:
    def __init__(
        self, blobs: BlobStoragePort, access: AccessControl, ids: IdPort
    ) -> None:
        self._blobs = blobs
        self._access = access
        self._ids = ids

    async def upload_image(
        self, caller: CallerContext, workspace_id: WorkspaceId, *, content: bytes
    ) -> UploadedFile:
        await self._access.require_workspace(caller, workspace_id, Role.EDITOR)
        if not content:
            raise ValidationFailed("empty file")
        if len(content) > MAX_IMAGE_BYTES:
            raise ValidationFailed("file too large (max 10 MB)")
        content_type = _sniff_image_type(content)
        if content_type is None:
            raise ValidationFailed(
                "unsupported image type (allowed: png, jpeg, gif, webp)"
            )
        file_id = self._ids.new_id()
        await self._blobs.put(
            _file_key(workspace_id, file_id), content, content_type=content_type
        )
        return UploadedFile(
            id=file_id,
            url=f"/api/v1/workspaces/{workspace_id}/files/{file_id}",
            content_type=content_type,
        )

    async def get_file(
        self, caller: CallerContext, workspace_id: WorkspaceId, file_id: str
    ) -> Blob | None:
        await self._access.require_workspace(caller, workspace_id, Role.VIEWER)
        return await self._blobs.get(_file_key(workspace_id, file_id))
